---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: invoices-svc
  name: invoices-svc
  namespace: default
spec:
  # A deployment's specification really only 
  # has a few useful options

  # How many copies of each pod do we want?  
  replicas: 3

  # Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      run: invoices-svc

  # How do want to update the pods?
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        run: invoices-svc
    spec:
      containers:
      - image: jlow999/invoices_svc:v2
        imagePullPolicy: IfNotPresent
        name: invoices-svc
        env:
        - name: EXPECTED_DATE_URI
          value: http://expected-date-svc.default.svc.cluster.local
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: invoices-svc
  name: invoices-svc
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  fws-invoices_mapping
      prefix: /invoices/
      rewrite: /api/invoices/
      service: invoices-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: invoices-svc
  sessionAffinity: None
  type: ClusterIP